#Comment: This is the configuration file for apnea-ppg
#The indented use is the definition of constants (like paths) used in project code.
---
paths:
  local: # relative or absolute paths using system slash (\ for windows, / for linux) without: ""
    edf_directory:
    xml_annotations_directory:
    subject_objects_directory:
    csv_directory:
    subset_1_directory:
    subset_1_training_directory:
    subset_1_saved_models_directory:
    subset_2_directory:
    subset_2_training_directory:
    subset_2_saved_models_directory:
    subset_3_directory:
    subset_3_training_directory:
    subset_3_saved_models_directory:
    pt_ocl_dll:
    dependency_dlls:

system:

  specs:
    compute_platform:

variables:
  dataset:
    subset:  # int
    convert_spo2desat_to_normal: False
    n_input_channels: 1
  models:
    net_type: # UNET or UResIncNet or ConvNet or ResIncNet
    net_identifier:
    kernel_size: 3
    depth: 8
    layers: 2
    sampling_method: conv_stride
    dropout:
    lstm_max_features: 128
    lstm_layers: 2
    lstm_dropout: 0.1
    use_weighted_loss: False
    class_weights:  # List of class weights
    custom_net_weight_init: False
  optimizer:
    type: "adam"
    lr:
    warmup: True
    warmup_ascending: True
other:
  ssh_pass: