#Comment: This is the configuration file for apnea-ppg
#The indented use is the definition of constants (like paths) used in project code.
---
paths:
  local: # relative or absolute paths using system slash (\ for windows, / for linux) without: ""
    edf_directory:
    xml_annotations_directory:
    subject_objects_directory:
    csv_directory:
    subset_1_directory: